### ISSUE TITLE
SINTESIS BUENAS PRÁCTICAS EN GESTIÓN DE PROYECTOS_MARIA JOSE LOPEZ LEYVA

### ISSUE THREAD

**Issue by MariaJose-1007** [SistemasTecTlaxiaco/actividad-3-sintesis-MariaJose-1007#2]
[SINTESIS_MARIA JOSE LOPEZ LEYVA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-MariaJose-1007/files/12504892/SINTESIS_MARIA.JOSE.LOPEZ.LEYVA.pdf)

**Comment by DiegoSCP117** [comment]
Calificación: 20

:3

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
